<?php
/** @brief Exercise profile ownership, quota ACL, stale defaults and deleted-account preservation. */
require __DIR__ . '/collections.php';
require __DIR__ . '/../../../pkg_audioarchive/com_audioarchive/administrator/src/Service/UserProfileService.php';
use Punga\Component\Audioarchive\Administrator\Service\UserProfileService;
$startChecks = $checks;
$db->pdo->exec("ALTER TABLE test_categories ADD title TEXT DEFAULT 'Category';
CREATE TABLE test_viewlevels (id INTEGER, title TEXT, ordering INTEGER);
INSERT INTO test_viewlevels VALUES (1,'Public',1),(2,'Registered',2);
ALTER TABLE test_audioarchive_user_profiles ADD default_visibility TEXT DEFAULT '';
ALTER TABLE test_audioarchive_user_profiles ADD default_category_id INTEGER DEFAULT 0;
ALTER TABLE test_audioarchive_user_profiles ADD default_access_id INTEGER DEFAULT 0;
ALTER TABLE test_audioarchive_user_profiles ADD storage_quota_override_bytes INTEGER;
ALTER TABLE test_audioarchive_user_profiles ADD clip_quota_override INTEGER;
CREATE TABLE test_audioarchive_group_quotas (group_id INTEGER, storage_quota_bytes INTEGER, clip_quota INTEGER);
CREATE TABLE test_audioarchive_files (clip_id INTEGER, file_role TEXT, file_size INTEGER);
");
$owner->permissions['core.create'] = true;
Joomla\CMS\Factory::$users[7] = $owner;
$options->data['frontend_allowed_access'] = [1,2];
$options->data['allow_private_clips'] = 1;
$profile = new UserProfileService($db, $options, $owner);
check($profile->canEdit(7) && !$profile->canEdit(8), 'profile owner isolation');
rejectContribution(fn() => $profile->read(8), 'foreign profile inaccessible');
rejectContribution(fn() => $profile->save(7, ['clips_mode'=>'unlimited']), 'ordinary user cannot set quota');
rejectContribution(fn() => $profile->save(7, ['clip_quota_override'=>-1]), 'raw quota field cannot bypass ACL');
$profile->save(7, ['default_visibility'=>'registered', 'default_category_id'=>2, 'default_access_id'=>2]);
check($profile->read(7)['default_visibility'] === 'registered', 'registered default retained');
$owner->permissions['core.create'] = false;
$profile->save(7, ['default_visibility'=>'private', 'default_category_id'=>2]);
check((int) $profile->read(7)['default_category_id'] === 0 && $profile->read(7)['default_visibility'] === '', 'revoked category ACL falls back safely');
rejectContribution(fn() => $profile->save(7, ['default_soundboard_id'=>999]), 'foreign or missing board rejected');
$admin = new Joomla\CMS\User\User(9, ['core.manage'=>true,'core.edit'=>true,'audioarchive.quota.override'=>true]);
$manager = new UserProfileService($db, $options, $admin, true);
$manager->save(7, ['storage_mode'=>'custom','storage_mb'=>'23','clips_mode'=>'unlimited']);
$row = $profile->read(7);
check((int) $row['storage_quota_override_bytes'] === 23*1048576 && (int) $row['clip_quota_override'] === -1, 'admin quota units and unlimited');
$manager->save(7, ['storage_mode'=>'inherit','clips_mode'=>'custom','clips_limit'=>'0']);
check($profile->read(7)['storage_quota_override_bytes'] === null && (int) $profile->read(7)['clip_quota_override'] === 0, 'inherit clears override and zero remains a limit');
rejectContribution(fn() => $manager->save(7, ['clips_mode'=>'custom','clips_limit'=>['999']]), 'array injection rejected');
$options->data['quota_clips_enabled'] = 1;
check($profile->summary(7)['quota_status'] === 'PLG_USER_AUDIOARCHIVE_OVER_QUOTA', 'effective usage includes retained clips');
$db->pdo->exec("UPDATE test_audioarchive_collections SET share_token='orphan-token' WHERE user_id=7");
$count = (int) $db->setQuery('SELECT COUNT(*) FROM test_audioarchive_collections WHERE user_id=7')->loadResult();
$db->pdo->exec('DELETE FROM test_users WHERE id=7');
rejectContribution(fn() => $guestService->shared('orphan-token'), 'orphan share blocked even before plugin cleanup');
$profile->deleted(7);
check((int) $db->setQuery('SELECT COUNT(*) FROM test_audioarchive_collections WHERE user_id=7')->loadResult() === $count, 'account deletion preserves collections');
check((int) $db->setQuery('SELECT COUNT(*) FROM test_audioarchive_collections WHERE share_token IS NOT NULL')->loadResult() === 0, 'account deletion revokes share tokens');
check($db->lockBalance === 0, 'profile owner locks released after success and failure');
echo ($checks - $startChecks) . " user-profile assertions passed.\n";
